[world.size]
width = 20
height = 40

[world.factions]
energy_per_faction = 5
total_factions = 4

[world.worldgen]
min_req_base_distance = 7
water_coverage = 0.15
forest_coverage = 0.20
mountains_coverage = 0.05

[world.cells]
Empty = { cost = 1, vision = 0, capture_result = "Territory" }
Base = { cost = 1, vision = 5, capture_result = "Fortress" }
Territory = { cost = 1, vision = 5, capture_result = "Fortress" }
Fortress = { cost = 999, vision = 5, capture_result = "Fortress" }
Forest = { cost = 2, vision = 0, capture_result = "Territory" }
Water = { cost = 4, vision = 0, capture_result = "Bridge" }
Mountain = { cost = 3, vision = 0, capture_result = "Territory" }
Bridge = { cost = 1, vision = 5, capture_result = "Bridge" }

world.fog_of_war_enable = true

[ai]
ai_count = 3

[terminal]
offset_x = 20
offset_y = 5
